### ISSUE TITLE
Memory Errors

### ISSUE THREAD

**Issue by momocat-aric** [xapha/IBIS_Temporal#1]
**System Information:** 

- OS: Ubuntu 16.04 LTS

- Compiler: GCC 5.4.0

**Detailed description**
  When I run the code,  some errors occur sometimes, all of them are about memory errors:
  (the command I run is :  ./IBIS_Temporal 300 20 ./video.mp4
    video details: Type: MPEG-4 video  FPS 30)
-----------------------------------Errors-------------------------------------------------------------------
Temporal IBIS - 
sb.st_mode : 33279
S_IFMT : 61440
file type : 32768
single file processing
sh: 1: Syntax error: "(" unexpected
-frame	0
-frame	30
-frame	60
-frame	90
*** Error in `./IBIS_temporal': corrupted size vs. prev_size: 0x0000000000e9bf10 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f5581a967e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7e9dc)[0x7f5581a9d9dc]
/lib/x86_64-linux-gnu/libc.so.6(+0x81cde)[0x7f5581aa0cde]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f5581aa3184]
/usr/local/lib/libopencv_core.so.3.1(_ZN2cv10fastMallocEm+0x22)[0x7f5582bb1682]
/usr/local/lib/libopencv_core.so.3.1(_ZN2cv3Mat6createEiPKii+0x761)[0x7f5582a10841]
./IBIS_temporal(_ZN2cv3Mat6createEiii+0xa1)[0x40ceb5]
./IBIS_temporal(_ZN2cv3MatC2ENS_5Size_IiEEi+0xcd)[0x423649]
./IBIS_temporal(_Z12execute_IBISiiP4IBISP17Signal_processingPN2cv3MatENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x102)[0x420f7b]
./IBIS_temporal(main+0x48a)[0x422c73]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f5581a3f830]
./IBIS_temporal(_start+0x29)[0x40c639]
======= Memory map: ========
00400000-0042a000 r-xp 00000000 08:16 85199666                           /home/wy/IBIS_Temporal/build/IBIS_temporal
00629000-0062a000 r--p 00029000 08:16 85199666                           /home/wy/IBIS_Temporal/build/IBIS_temporal
0062a000-0062b000 rw-p 0002a000 08:16 85199666                           /home/wy/IBIS_Temporal/build/IBIS_temporal
00983000-08c99000 rw-p 00000000 00:00 0                                  [heap]
10000000-10001000 rw-s 00000000 00:06 550                                /dev/nvidia0
10001000-10002000 rw-s 00000000 00:06 550                                /dev/nvidia0
207000000-207004000 rw-s 00000000 00:06 549                              /dev/nvidiactl
20ca00000-300200000 ---p 00000000 00:00 0 
10000000000-10200800000 ---p 00000000 00:00 0 
10200800000-10200a00000 rw-s 00000000 00:05 39469                        /dev/zero (deleted)
10200a00000-10200c00000 rw-s 00000000 00:06 549                          /dev/nvidiactl
7f55047bf000-7f55047d3000 r-xp 00000000 08:16 22815454                   /usr/lib/x86_64-linux-gnu/libtdb.so.1.3.8
7f55049d4000-7f55049db000 r-xp 00000000 08:16 22809126                   /usr/lib/x86_64-linux-
7f552017d000-7f552037c000 ---p 00005000 08:16 23200507                   /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libunity-gtk-module.so
7f552037c000-7f552037d000 r--p 00004000 08:16 23200507                   /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libunity-gtk-module.so
7f552037d000-7f552037e000 rw-p 00005000 08:16 23200507                   /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libunity-gtk-module.so
7f5520ffa000-7f5520ffb000 ---p 00000000 00:00 0 
7f5520ffb000-7f55217fb000 rwxp 00000000 00:00 0 
7f55217fb000-7f55217fc000 ---p 00000000 00:00 0 
7f55217fc000-7f5521ffc000 rwxp 00000000 00:00 0 

7f55283f3000-7f55283f4000 r-xp 00000000 08:16 23200502                   /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7f55283f4000-7f55285f3000 ---p 00001000 08:16 23200502                   /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7f55285f3000-7f55285f4000 r--p 00000000 08:16 23200502                   /usr/lib/x86_64-linux-gnu/gtk-
7f556ee58000-7f556f058000 ---p 00011000 08:16 22815450                   /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1Aborted (core dumped)
-------------------------------------------------Errors--------------------------------------------------------------------------

when the errors above don't occur,  the "Segmentage fault" occurs， just like this:
nvalid freq measure : -2147483648
invalid freq measure : -2147483648
size_signals: 300 tentative HR 0
invalid freq measure : -2147483648
invalid freq measure : -2147483648
invalid freq measure : -2147483648
invalid freq measure : -2147483648
invalid freq measure : -2147483648
invalid freq measure : -2147483648
invalid freq measure : -2147483648
Segmentation fault (core dumped)

Are there bugs in the programe or I run the code in a wrong way?

**Comment by xapha** [comment]
Hi,

Sorry about that, it was my mistake, i uploaded a testing version of my code i am currently working on.

The current version has been tested and should work just fine, let me know if anything go wrong.

Sincerely
