### ISSUE TITLE
About OpenCV version

### ISSUE THREAD

**Issue by xilin-x** [xapha/IBIS_Temporal#2]
What version of OpenCV use in IBIS_Temporal projects?  I tried to use OpenCV 3.2.0 in this, but it does not work. 

**System Information**
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04) 

**Detailed Description:**
When I run the code, some errors occur sometimes, all of them are about OpenCV:
**the command :** ./IBIS_temporal 30 20 ./data/videos
video details: Type: AVI video FPS 30

------------------------------------------error message--------------------------------------------------------

 - Temporal IBIS -  

directory processing
 1 file(s) identified
processing stationary.avi
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/username/Programdata/opencv-3.2.0/modules/imgproc/src/color.cpp, line 9834
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/username/Programdata/opencv-3.2.0/modules/imgproc/src/color.cpp:9834: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor

Aborted (core dumped)

------------------------------------------------------------------------------------------------------------------------

Are there bugs in the program or I run the code in a wrong way?

**Comment by xapha** [comment]
OpenCV version is now specified in the home page of this project. With late 3.X version and then 4.X version, OpenCV has gone through a lot of modifications on flags and old c-version functions. As a consequence i have fixed the version you should use to run this program as i do not have the time making modifications for each and every OpenCV version.
